plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.mycontentapp'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.mycontentapp"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
